config/routes.rb
Rails.application.routes.draw do
  root 'books#welcome'
  devise_for :users
  get 'books/welcome' => 'books#welcome', as: :welcome
  get 'home/about' => 'books#about', as: :about
  resources :users, only: [:index,:show, :edit, :update]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :title,presence: true

  validates :body,
  presence: true,
  length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment,presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book,optional: true
  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
    
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, 
         :validatable
        # , :authentication_keys => [:login]

  # has_many :post_images, dependent: :destroy
  # attr_accessor :login

  validates :name,
  :uniqueness => {
    :case_sensitive => false
  }

  # def self.find_first_by_auth_conditions(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if login = conditions.delete(:login)
  #     where(conditions).where(["name = :value OR lower(email) = lower(:value)", { :value => login }]).first
  #   else
  #     where(conditions).first
  #   end
  # end
  
  
  validates :name,
  uniqueness: { case_sensitive: :false },
  length: { minimum: 2, maximum: 20 }
  
  validates :introduction,
  length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# before_action :authenticate_user!

before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource) 
    user_path(current_user)
  end

  protected
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :user_icon,:username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_user
  before_action :move_to_signed_in, except: [:welcome,:about]

  def move_to_signed_in
    unless user_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to  '/users/sign_in'
    end
  end
  def index
    @books=Book.all
    @book=Book.new
  end

  def create
    @books=Book.all
    @book = Book.new(book_params)
    @book.user_id = @user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(id: @book)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id === @user.id
      redirect_to  books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "Book was successfully updated.."
    else
      flash[:alert] = "Book was not updated error."
      # redirect_to book_path(book)
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
    @finduser = @book.user
    @booknew=Book.new
    @book_comment = BookComment.new
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      redirect_to books_path
      flash[:notice] = "Book was successfully destroyed."
    else
      flash[:alert] = "Book was not destroyed error."
    end
  end
  def welcome
  end
  def about
  end

  private
  def set_user
    @user = current_user
  end
  def book_params
     params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save!

    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
     redirect_to request.referer
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :move_to_signed_in

  def move_to_signed_in
    unless user_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to  '/users/sign_in'
    end
  end
  
  def index
    @users = User.all
    @book=Book.new

    # @books = @user.books.reverse_order
    # byebug
  end
  def show
    @finduser = User.find(params[:id])
    @books = @finduser.books.reverse_order
    # byebug
    @book=Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = @user.id
    if @book.save
      flash[:notice] = "Book was successfully updated.."
      redirect_to book_path(id: @book)
    else
      render :index
    end
  end
  
  def edit
    finduser = User.find(params[:id])
    unless @user == finduser
      redirect_to  user_path(@user)
    end
  end

  def update
    @finduser = User.find(params[:id])
    # byebug
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "User was successfully updated.."
    else
      flash[:alert] = "User was not updated."
      # redirect_to book_path(book)
      render :edit
    end
  end

  private
  def set_user
    @user = current_user
  end
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<h2 >Books</h2>
<table width="100%">
   <tr class= "bordery">
     <th height="40"></th>
     <th>Title</th>
     <th>Option</th>
   </tr>
   <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg",size:'40x40' %>
        <% end %>
      </td>
      <td  height="40" class="m-1"><%= link_to book.title , book_path(book) ,class:"m-1" %></td>
      <td class="m-1"><%= book.body  %></td>
      <td>
        <% if book.favorited_by?(current_user) %>
          <%= link_to book_favorites_path(book), method: :delete, class: 'text-danger text-decoration-none' do %>
            <i class="fas fa-heart"></i>
            <%= book.favorites.count %>
          <% end %>
        <% else %>
          <%= link_to book_favorites_path(book), method: :post, class: 'text-primary text-decoration-none' do %>
            <i class="fas fa-heart"></i>
            <%= book.favorites.count %>
          <% end %>
        <% end %>
      </td>
      <td class="m-1"><%= link_to "コメント数：#{book.book_comments.count}", book_path(book.id) %></td>
    </tr>
   <% end %>
</table>

app/views/books/_newbook.html.erb
  <h2>New book</h2>
<%= form_with(model: book, local: true) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <p>
      <%= f.submit 'Create Book',class:"btn btn-success" %>
    </p>

  <% end %>

app/views/books/_profile.html.erb
  <div>
    <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg" ,size:'100x100'%>
    <div class="d-flex justify-content-between bordery">
      <p class="m-0">name</p>
      <p class="m-0"><%= user.name %></p>
    </div>
    <p class="pt-2">introduction  <%= user.introduction %></p>
    <%= link_to  "", edit_user_path(user),class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>

app/views/books/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>
<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/books/edit.html.erb
</div>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <% if @book.errors.any? %>
          <%= @book.errors.count %>件のerror発生しました
          <% @book.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        <% end %>
        <h2>Editing Book</h2>
         </br>
         <%= form_with(model: @book, local: true) do |f| %>
          <label for="inputName">Title</label>
          <%= f.text_field :title, autofocus: true, class:"mb-4 p-0 form-control w-100 margincenter",placeholder:"タイトル"%>


          </br>

          <label for="inputImage">introduction</label>
          <%= f.text_area :body, autofocus: true, class:"mb-4 p-0 form-control w-100 margincenter",placeholder:"本文"%>

          <%= f.submit "Update Book",class:"btn btn-secondary" %>
        <% end %>
        
                
        <P class="ml-3"><%= link_to "Show", book_path %> | <%= link_to "Back", books_path %></P>


      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerror発生しました
  <% @book.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>
  <p class="notice"><%= notice %></p>
  <div class="row">
    <div class= "col-md-3">
      <%= render 'books/profile', user: @user %>
      <%= render 'books/newbook', book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <%= render 'books/index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerror発生しました
  <% @book.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>
  <p class="notice"><%= notice %></p>
  <div class="row">
    <div class= "col-md-3">
      <%= render 'books/profile', user: @book.user %>
      <%= render 'books/newbook', book: @booknew %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table width="100%">
         <tr class= "bordery">
           <th height="40"></th>
           <th>Title</th>
           <th>Option</th>
         </tr>

          <tr>

            <td>
              <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag @book.user, :profile_image, fallback: "no_image.jpg",size:'40x40' %>
              <% end %>
              <br><%= link_to @book.user.name, user_path(@finduser)%>
            </td>
            <td  height="40" class="m-1"><%= link_to @book.title , book_path(@book) ,class:"m-1" %></td>
            <td height="40" class="m-1"><%= @book.body  %></td>
            <% if @user === @finduser %>
              <td> <%= link_to "Edit" , edit_book_path(@book) ,class:"m-1 btn btn-sm btn-success edit_book_19631" %></td>
              <td> <%= link_to 'Destroy' , book_path(@book), method: :delete, data:{ confirm: "Are You sure" },class:"m-1 btn btn-sm btn-danger destroy_book_19631"%></td>
            <% end %>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(@book), method: :delete, class: 'text-danger text-decoration-none' do %>
                    <i class="fas fa-heart"></i>
                    <%= @book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(@book), method: :post, class: 'text-primary text-decoration-none' do %>
                    <i class="fas fa-heart"></i>
                    <%= @book.favorites.count %>
                  <% end %>
                <% end %>
              </td>
          </tr>
      </table>
      <div>
        <p>コメント数：<%= @book.book_comments.count %></p>
        <% @book.book_comments.each do |book_comment| %>
          <%= attachment_image_tag book_comment.user, :profile_image, fallback: "no_image.jpg",size:'40x40' %>
          <%= book_comment.user.name %>
          <%= book_comment.comment %>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete,class:"m-1 btn btn-sm btn-danger destroy_book_19631"  %>
          <% end %>
        <% end %>
        </div>
        <div>
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" ,rows: '5', cols: '100'%>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/welcome.html.erb
  <p class="notice"><%= notice %></p>
<main>
  <p id="notice"></p>
  <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <p class="btn btn-info btn-sm btn-block mb-3 sign_in"> <%= link_to "Log in", new_user_session_path,class:"text-white" %></p>
        </div>
        <div class="row">
          <p class="btn btn-success btn-sm btn-block sign_up"><%= link_to "Sign up", new_user_registration_path ,class:"text-white"%></p>
        </div>
      </div>
    </div>
  </div>
</div>
</main>
<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boockers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <% if user_signed_in? %>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li><p class="fas fa-home nav-link text-light text-white" > <%= link_to 'Home', user_path(id: current_user.id), class:"text-light" %></p></li>
              <li><p class="fas fa-users nav-link text-light"> <%= link_to 'Users', users_path , class:"text-light" %></p></li>
              <li><p class="fas fa-book-open nav-link text-light"> <%= link_to 'Books', books_path , class:"text-light"%></p></li>
              <li><p class="fas fa-sign-out-alt nav-link text-light"><%= link_to "logout", destroy_user_session_path, method: :delete , class:"text-light"%></p></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <br>
    <% else %>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li><p class="fas fa-home nav-link text-light"> <%= link_to "Home", root_path , class:"text-light"%></p></li>
              <li><p class="fas fa-link nav-link text-light"> <%= link_to "About", about_path , class:"text-light"%></a></li>
              <li><p class="fas fa-user-plus nav-link text-light">  <%= link_to "sign up", new_user_registration_path , class:"text-light"%></p></li>
              <li><p class="fas fa-sign-in-alt nav-link text-light"> <%= link_to "login", new_user_session_path , class:"text-light"%></p></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <br>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <% if @user.errors.any? %>
          <%= @user.errors.count %>件のerror発生しました
          <% @user.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        <% end %>
        <h2>User info</h2>
         </br>
        <%= form_with model:@user, local:true do |f| %>
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, class:"mb-4 p-0 form-control w-100 margincenter",placeholder:"ユーザーネーム"%>

          <label for="inputImage">image</label>
          </br>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </br></br>

          <label for="inputImage">introduction</label>
          <%= f.text_area :introduction, autofocus: true, class:"mb-4 p-0 form-control w-100 margincenter",placeholder:"自己紹介"%>

          <%= f.submit "Update User",class:"btn btn-secondary" %>
        <% end %>
        
        <P class="ml-3"><%= link_to "Show", book_path %> | <%= link_to "Back", books_path %></P>

      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerror発生しました %>
  <% @book.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>
  <p class="notice"><%= notice %></p>
  <div class="row">
    <div class= "col-md-3">
      <%= render 'books/profile', user: @user %>
      <%= render 'books/newbook', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table width="100%">
         <tr class= "bordery">
           <th height="40">image</th>
           <th>name</th>
           <th></th>
         </tr>
         <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to user_path(user) do %>
                <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg",size:'40x40' %>
              <% end %>
            </td>
            <td height="40" class="m-1"><%= user.name  %></td>
            <td  height="40" class="m-1"><%= link_to "Show" , user_path(user) ,class:"m-1" %></td>
          </tr>
         <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerror発生しました
  <% @book.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>
  <p class="notice"><%= notice %></p>
  <div class="row">
    <div class= "col-md-3">
      <%= render 'books/profile', user: @finduser %>
      <%= render 'books/newbook', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <%= render 'books/index', books: @books %>
    </div>
  </div>
</div>